name: Python2 DLL Release
run-name: Building Python2 Release DLL🚀
on: workflow_dispatch
jobs:
  Building-Actions:
    runs-on: windows-2022
    steps:
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.3.1
        with:
          vs-version: '[17.6,]'

      - name: Build Release DLL
        run: cd PCbuild
        run: build.bat -p x64 -c Release --no-tkinter